CREATE TABLE `action` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoryHash` VARCHAR(128) DEFAULT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `detail` TEXT DEFAULT NULL,
  `behavior` TEXT DEFAULT NULL,
  `result` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE action_summary (
  `hash` VARCHAR(32) NOT NULL,
  `trust` TINYINT UNSIGNED NOT NULL,
  `summary` TEXT NOT NULL,
  PRIMARY KEY (`hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE config (
  `code` VARCHAR(50) NOT NULL,
  `value` TEXT NOT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
