<?php

namespace Anodet\Core\Contracts;

use Anodet\Core\Value\Action;
use Anodet\Core\Value\Result;

interface Analyzer extends Module
{
    /**
     * This function is useful to filter the actions generated by the transporter.
     * i.e: Only actions with (isset($action->getDetail['cpuLoad'])
     * If it returns true, the action will pass to the analyze method.
     * @param Action $action
     * @return bool
     */
    public function supports(Action $action);


    /**
     * Do anything with a the actions generated by the transporter and supported by this analyzer.
     * @param Action[] $action
     * @return Result
     */
    public function analyze($action);

}
