<?php

namespace Anodet\Core\Contracts;

use Anodet\Core\Value\Notification;
use Anodet\Core\Value\Result;

interface Decider extends Module
{
    /**
     * This function is useful to filter all the results generated by analyzers.
     * If it returns true, the result will pass to the decide method.
     * @param Result $result
     * @return bool
     */
    public function supports(Result $result);

    /**
     * @param Result $result
     * @return Notification
     */
    public function decide(Result $result);
}
